apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-f6lk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-f6lk
    app.kubernetes.io/part-of: tkrw-pr712-0075-0072-app
  name: devfile-sample-f6lk
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-f6lk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-f6lk
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0072-tenant/tkrw-pr712-0075-0072-app/devfile-sample-f6lk@sha256:3fdbd5c9bb89e11bf721972d97e0a3aa5d1e81fddc52a2f3cff01fc8c93861cb
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
